
FEAT_ADIR_MAX_SEV     = 'adir_max_severity'
FEAT_ADIR_MIN_SEV     = 'adir_min_severity'
FEAT_ADIR_SEV_0_CNT   = 'adir_severity_0_count'
FEAT_ADIR_SEV_1_CNT   = 'adir_severity_1_count'
FEAT_ADIR_SEV_2_CNT   = 'adir_severity_2_count'
FEAT_ADIR_SEV_3_CNT   = 'adir_severity_3_count'
FEAT_ADIR_SEV_4_CNT   = 'adir_severity_4_count'


KEY_CRITERION         = 'criterion'
KEY_MAX_FEAT          = 'max_features'
KEY_MAX_DEPTH         = 'max_depth'
KEY_N_ESTIM           = 'n_estimators'
KEY_FEAT_ENCMAP       = 'feature_encoding_map'
KEY_OUT_COL           = 'outcome_column'
KEY_DUNNO_RANGE       = 'dunno_range'
KEY_CLS_WEIGHT        = 'class_weight'
KEY_BALANCE_DIM       = 'balancing_dimensions'
KEY_BOOT_TRIES        = 'bootstrapping_number_of_tries'
KEY_BOOT_PERC         = 'bootstrapping_sample_percent'
KEY_OUTCOME_CLS       = 'outcome_classes'
KEY_OUTCOME_CLS_PRIOR = 'outcome_class_priors'
KEY_YOUNG_SAMPLE      = 'young_sample'
KEY_WITHOUT_DUNNO     = 'without_dunno'
KEY_WITH_DUNNO        = 'with_dunno'
